{
 "title": "Postgresql Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Database stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query statistics",
   "type": "table",
   "description": "Shows basic database query statistics",
   "gridPos": { "h": 14, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select * from recent_query_stats();"
    }
   ]
  },
  {
   "title": "Status",
   "type": "gauge",
   "description": "Shows green when database is up",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN EXISTS (SELECT 1 ) THEN 1 ELSE 0 END AS status;"
    }
   ]
  },
  {
   "title": "Concurrent connections",
   "type": "piechart",
   "description": "Shows all connections to db",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT datname AS Database, count(*) AS \"Connections\"\r\nFROM pg_stat_activity\r\nwhere datname is not null\r\nGROUP BY datname;"
    }
   ]
  }
 ]
}